# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_date', models.DateTimeField(auto_now=True)),
                ('comments_modify_date', models.DateTimeField(auto_now_add=True)),
                ('comments_text', models.TextField()),
                ('comments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User')),
                ('comments', models.ManyToManyField(to='post.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postlike_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('postlike_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(related_name='liked_user', through='post.PostLike', to='member.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post.Tag'),
        ),
    ]
