# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postlike_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=True,
        ),
    ]
