# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170612_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
